### ISSUE TITLE
Add instructions to run VM with QEMU

### ISSUE THREAD

**Issue by paulmenzel** [open-switch/opx-docs#32]
The [current instructions for running OPX in a virtual machine](https://github.com/open-switch/opx-docs/wiki/Run-virtual-machine) are quite cumbersome requiring to execute some untrusted binary `lvm`.

Please provide an image usable with QEMU/KVM, and document the instructions for that.

**Comment by jghalam** [comment]
There are many ways to run OPX VM. The simplest way is to use vagrant. You can refer to the section called "Connect to Vagrant box” at the link you included.

The lvm tool that you are referencing is a self-contained byte compiled python script (to eliminate needs for installing packages and python / python tools) which allows you to build a vm from scratch. I’m not sure what makes the byte-compiled lvm an untrusted tool but it simplifies the following septs to build of a VM:
create a generic white-box switch profile using VirtualBox
install and embed ONIE
allow ONIE installer to discover and install OPX onie-installer
configure accounts and basic access to the device

**Comment by mikelazar** [comment]
In order to install OPX in any VM environment (QEMU is one of them), there are two steps:
- install the KVM version of ONIE
- install OPX using the ONIE installation process.
LVM automates that process for Virtual Box and/or Vagrant.

If you want to use QEMU, for the first step, you can use the instructions at:
https://opencomputeproject.github.io/onie/design-spec/x86_recovery.html to create an ONIE VM

For the second step you can follow the OPX instructions for "real" HW - the ONIE interface is the same:
https://github.com/open-switch/opx-docs/wiki/Install-OPX-on-Dell-EMC-ON-Series-platforms

**Comment by mikelazar** [comment]
I am closing this issue, as per Joe's reply. 
In addition, the instructions for installing ONIE (thus OPX) on QEMU are available in the ONIE wiki.
